# Generated by Django 5.2.6 on 2025-10-16 01:13

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_route_latitude_route_location_name_route_longitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                models.F("author"),
                name="uniq_route_title_per_user_ci",
            ),
        ),
    ]
