# Generated by Django 5.2.6 on 2025-10-16 01:53

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_alter_route_latitude_alter_route_longitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={
                "ordering": [django.db.models.functions.text.Lower("title"), "id"]
            },
        ),
        migrations.RemoveConstraint(
            model_name="route",
            name="uniq_route_title_per_user_ci",
        ),
    ]
